// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApAmEIj6T5IAK78MFQgplFiQoMzspRZKY',
    appId: '1:954628953640:android:5e3e2d6b79c72f6b59071d',
    messagingSenderId: '954628953640',
    projectId: 'cis-3334-project2-brianmichaud',
    storageBucket: 'cis-3334-project2-brianmichaud.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsyZ_YgAtSS171Cd6xVIUpUSX4AmIMFxk',
    appId: '1:954628953640:ios:4b788cee3c531e7559071d',
    messagingSenderId: '954628953640',
    projectId: 'cis-3334-project2-brianmichaud',
    storageBucket: 'cis-3334-project2-brianmichaud.appspot.com',
    iosClientId: '954628953640-43gltk1htukna1lvt23hdjpvtiq19c8u.apps.googleusercontent.com',
    iosBundleId: 'com.example.project2',
  );
}
